### ISSUE TITLE
Sprawdzanie zakresów dla prostokąta

### ISSUE THREAD

**Issue by krzysztof9nowak** [Flowyh/KP-SEM2#2]
Jak zrobisz prostokąt 1 x 181 to spadnie z rowerka

      if (param1 <= 0 || param2 <= 0)
        throw new IllegalArgumentException("Given number is not natural");
      if (param2 >= 180)
        throw new IllegalArgumentException("Angle can't be bigger than 180");

**Comment by Flowyh** [comment]
O rzeczywiście, słuszna uwaga. Już dopisałem check czy to jest romb. 5cb6f0d82592068e7ea54f4d372cf2337c46bcfd
